layout: default
name: Voron Documentation
description: Voron Official and Community Documentation
logo: "/images/voron_design_logo.png"
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
color_scheme: light
search_enabled: true
aux_links:
  "Voron Docs on GitHub":
    - "//github.com/bdbell/VoronDocs"

